### ISSUE TITLE
[updateDatabase] Failed to fetch etag from url.

### ISSUE THREAD

**Issue by flynncao** [ykozxy/bangumi-sync#12]
运行`npm run start`后提示，Anilist和Bangumi的token已经正常获取。
请问这种情况是网络问题吗？
```
[updateDatabase] Failed to fetch etag from url.
getaddrinfo EAI_FAIL cdn.jsdelivr.net
Error: getaddrinfo EAI_FAIL cdn.jsdelivr.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
Cannot read properties of undefined (reading 'reduce')
TypeError: Cannot read properties of undefined (reading 'reduce')
    at Object.loadData (D:\Github\bangumi-sync-forked\build\types\china_anime_data.js:15:27)
    at D:\Github\bangumi-sync-forked\build\utils\data_util.js:45:89
    at Generator.next (<anonymous>)
    at fulfilled (D:\Github\bangumi-sync-forked\build\utils\data_util.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by flynncao** [comment]
我使用了V2RayN下开启TUN模式后正常。难道发起的不是http/https请求？

**Comment by Misaka13514** [comment]
可能是你命令行没成功走代理吧

**Comment by flynncao** [comment]
> 可能是你命令行没成功走代理吧

应该不是这个问题，我开启system proxy时不修改任何配置下就可以 `curl https://google.com/` 成功

---

如果手动配置环境变量，也是会得到一样的结果，检查了v2rayN DNS servers默认是`1.1.1.1`和`8.8.8.8`

![image](https://github.com/user-attachments/assets/35e1ab5a-5c0c-4350-bc6c-95f0d549da17)
